---
- name: Copy Script for all system
  copy:
    src: 'files/{{ item }}'
    dest: /home/nghialv/
    owner: nghialv
    group: nghialv
    mode: o=x
  with_items:
    - backup_remote.sh
    - backup_local.sh

- name: Create Job for All system
  cron:
    name: Run Script Backup To Remote
    minute: '0'
    hour: '23'
    job: "bash /home/nghialv/backup_remote.sh"
    user: nghialv
    state: present

- name: Create Job 2 for system
  cron:
    name: Run Script Backup To Local
    hour: '*/2'
    job: "bash /home/nghialv/backup_local.sh"
    user: nghialv
    state: present
